### ISSUE TITLE
API-Pod restarts quite often

### ISSUE THREAD

**Issue by Roemer** [Visual-Regression-Tracker/Visual-Regression-Tracker#345]
Hello

We have the issue that the API pod restarts about every one or two days. See this chart:
![image](https://user-images.githubusercontent.com/393641/152555883-08ab2fda-f4bd-4d6b-9bab-be34f9a5d8e7.png)

What I can see is that the CPU usuall is higher just before a restart, but I increased the Pod CPU reservation already quite a bit (3 cpus now). Also in the Kubernetes log all I could find right now is just:
```
containerStatuses:
  - containerID: containerd://xxxxxxxxxxxxxxxxxxxxxxxxxx
    image: docker.io/visualregressiontracker/api:4.19.0
    imageID: docker.io/visualregressiontracker/api@sha256:97f732db43387bf6c51b3309841959577b527c229d6301c2cd2b0f7927595a84
    lastState:
      terminated:
        containerID: containerd://yyyyyyyyyyyyyyyyyyyyyyyyyyyyy
        exitCode: 0
        finishedAt: "2022-02-03T16:05:16Z"
        reason: Completed
        startedAt: "2022-02-01T07:45:37Z"
```
What could be the cause? It seems that the pod just finished? Is there anyting I can do to debug this more?
