### ISSUE TITLE
Issue with proxying in production environment.

### ISSUE THREAD

**Issue by SwiLink** [Visual-Regression-Tracker/Visual-Regression-Tracker#414]
Hey! 

Have issue with deploying it. Have used you Quick Setup guide. Need to proxy with Docker via nginx. All is deploying well, but then meet the issue that your sockets requests are sending to http:localhost:4200(screenshot attached), but in .env i have defined another url, where i need to define it and how is it related? Even sometimes it's starting to work well - like i was sitting at night and it was working(proxying to my url), then i went to sleep and in the morning it's stopped to work(one more time started to send socket requests to http:localhost:4200)  without any dos from my side.
![image](https://github.com/Visual-Regression-Tracker/Visual-Regression-Tracker/assets/91793217/fa7aac4d-dbd2-4e88-9fea-ae4359622f31)

For example - my website is https://mywebsite.com, backend is on https://mywebsite.com/api.

Here is my configuration:

My .env now:
```
## Logging
# https://www.elastic.co/guide/en/elastic-stack/7.14/overview.html
ELK_VERSION=7.14.1
ELASTIC_URL=http://localhost:9200

## VRT version
VRT_UI_VERSION=4.22.0
VRT_API_VERSION=5.0.0
VRT_MIGRATION_VERSION=4.20.1

## Frontend

# direct URL to backend with port (same as APP_PORT)
REACT_APP_API_URL=https://mywebsite.com/api
# frontend port
PORT=8080

## Backend

# direct URL to frontend with port (same as PORT)
APP_FRONTEND_URL=https://mywebsite.com
# backend port
APP_PORT=4200
# seed to generate JWT
JWT_SECRET=mysecret
# user session lifetime
JWT_LIFE_TIME=1d
# max image size to upload
BODY_PARSER_JSON_LIMIT="5mb"

## DB

POSTGRES_PORT=5432
POSTGRES_USER=postgres
POSTGRES_PASSWORD=postgres
POSTGRES_DB=vrt_db
```

My docker-compose.yaml:
```
version: "3.8" # Docker Engine minimum version 19.03.0
networks:
  proxy:
    name: mynetwork

services:
  ui:
    image: visualregressiontracker/ui:${VRT_UI_VERSION}
    ports:
      - "${PORT}:8080"
    # https config
    #   - "8080:8080"
    #   - "${PORT}:5000"
    volumes:
      - ./imageUploads:/usr/share/nginx/html/static/imageUploads
    #   - ./ssl/ssl.cert:/etc/nginx/secrets/ssl.cert
    #   - ./ssl/ssl.key:/etc/nginx/secrets/ssl.key
    #   - ./ssl/default.conf:/etc/nginx/conf.d/default.conf
    #   - ./ssl/nginx.conf:/etc/nginx/nginx.conf
    environment:
      REACT_APP_API_URL: ${REACT_APP_API_URL}
      VRT_VERSION: ${VRT_UI_VERSION}
    restart: always
    networks:
      - proxy
  api:
    image: visualregressiontracker/api:${VRT_API_VERSION}
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
      JWT_SECRET: ${JWT_SECRET}
      JWT_LIFE_TIME: ${JWT_LIFE_TIME}
      APP_FRONTEND_URL: ${APP_FRONTEND_URL}
      BODY_PARSER_JSON_LIMIT: ${BODY_PARSER_JSON_LIMIT}
      ELASTIC_URL: ${ELASTIC_URL}
    ports:
      - "${APP_PORT}:3000"
    volumes:
      - ./imageUploads:/imageUploads
      # https config
      # - ./ssl/ssl.cert:/secrets/ssl.cert
      # - ./ssl/ssl.key:/secrets/ssl.key
    depends_on:
     - postgres
    restart: always
    networks:
      - proxy
  migration:
    image: visualregressiontracker/migration:${VRT_MIGRATION_VERSION}
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
    depends_on:
      - postgres
    restart: on-failure
    networks:
      - proxy
  postgres:
    image: postgres:12
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:5432"
    expose:
      - "${POSTGRES_PORT}"
    volumes:
      - ./db:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $$POSTGRES_DB -U $$POSTGRES_USER"]
      interval: 10s
      timeout: 120s
      retries: 10
    networks:
      - proxy
```

My default.conf nginx configuration:
```
server {
        listen 80;
        listen 443;
        http2 on;

        server_name mywebsite.com;

   location ~ ^/api(/.*)?$ {
        rewrite ^/api(/.*)$ $1 break;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_pass http://api:3000;
    }

        location ~ / {
                proxy_pass http://ui:8080;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header Host $host;
        }

        location = / {
                proxy_pass http://ui:8080;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header Host $host;
    }

        location ~* ^.+\.(jpg|jpeg|gif|png|ico|css|pdf|ppt|txt|bmp|rtf|ttf|svg|js)$ {
                expires 2d;
                add_header Cache-Control public;
        }
}
```
